GAME = 'Breakout-v0'
REPLAY_MEMORY = 250000 # number of previous transitions to remember
NUM_ACTIONS = 6 # number of valid actions
GAMMA = 0.99 # decay rate of past observations
OBSERVE = 500. # timesteps to observe before training
EXPLORE = 100000 # frames over which to anneal epsilon
FINAL_EPSILON = 0.2 # final value of epsilon
INITIAL_EPSILON = 1.0 # starting value of epsilon
BATCH = 32 # size of minibatch
LEARNING_RATE = 0.000001
